[package]
name = "client"
version = "0.1.0"
authors = ["Victor Koenders <victor.koenders@gmail.com>"]

[dependencies]
urlencoding = "*"
serde_json = "*"
shared = { path = "../shared" }
actix = "*"
actix-web = "*"
futures = "0.1"
